### ISSUE TITLE
Can't get script to build DB

### ISSUE THREAD

**Issue by Shattymeal** [CarlosFdez/MHWorldData#2]
I finally got Python 3.6 with SQL Alchemy 1.2.5 on my computer and when I try to build I get this error:

Traceback (most recent call last):
  File "/Users/HumanShetty/Downloads/MHWorldData-master/build.py", line 144, in <module>
    build_armor(session)
  File "/Users/HumanShetty/Downloads/MHWorldData-master/build.py", line 128, in build_armor
    raise Exception(f"ERROR: Item {item} in Armor {armor_name_en} does not exist")
Exception: ERROR: Item Earth crystal in Armor High Metal Mail does not exist

Do you have any idea whats going on?

**Comment by Shattymeal** [comment]
Ended up downloading python 3.6.4 for windows and I was able to get the DB to build.

**Comment by CarlosFdez** [comment]
Sorry for the late reply. The reason the build failed was because there was an typo in the actual data (specifically in spelling earth crystal). I had recently corrected it.
